### PR TITLE
Fix the empty conda-forge.yml file to contain empty dict, rerender

### PR DESCRIPTION
**Pull request by Wentzell**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Wentzell** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Looks like this worked!

Note that when we merge the pypy migration, this hack will break again.

**Comment by isuruf** [comment]
Or if you add windows or py3 support

**Comment by Wentzell** [comment]
@beckermr Thanks! I will make sure to wrap up the Python3 ports quickly.

**Comment by beckermr** [comment]
On your other feedstocks, put this exact test in an issue title

`@conda-forge-admin add python 2.7`

The admin bot will make a PR and the change above for you.

**Pull request merged**
